<div class="item-container img-thumbnail">
    <div class="item-flipper">
        <div class="item-front">
            <!-- front content -->
            <a href="<?php echo $_product->getProductUrl() ?>"
               title="<?php
               echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true)
               ?>" class="product-image">
                <img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(250, 310); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="img-responsive" /></a>
        </div>
        <div class="item-back">
            <!-- back content -->
            <div class="book-info">
                <div class="h4"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a></div>
                <div class="short-description"><?php echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?></div>
            </div>
            <p><a href="<?php echo $_product->getProductUrl() ?>"
                  title="<?php echo $this->stripTags($_product->getName(), null, true) ?>" class="btn btn-block btn-success"><?php echo $this->__('Book Details') ?></a></p>
        </div>
    </div>
</div>